### ISSUE TITLE
'Cannot read property' issue

### ISSUE THREAD

**Issue by tobydeh** [neoclide/coc-tslint#3]
The latest changes seem to have caused an issue.... was working fine yesterday.

![image](https://user-images.githubusercontent.com/82720/59842675-eb8b0700-934e-11e9-9a68-12181468ed47.png)

```
[Info  - 11:09:48 AM] TSLint library loaded from: /Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/index.js
The 'interface-over-type-literal' rule threw an error in '/Volumes/HD2/Development/Repos/xxx/mobile/app/store/auth.ts':
TypeError: Cannot read property 'kind' of undefined
    at Object.isTypeLiteralNode (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tsutils/typeguard/2.8/node.js:640:17)
    at cb (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/interfaceOverTypeLiteralRule.js:50:65)
    at visitNodes (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16631:30)
    at Object.forEachChild (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16910:24)
    at walk (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/interfaceOverTypeLiteralRule.js:49:15)
    at Rule.AbstractRule.applyWithFunction (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/interfaceOverTypeLiteralRule.js:29:21)
    at Linter.applyRule (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:214:29)
    at /Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/utils.js:160:29)
The 'no-shadowed-variable' rule threw an error in '/Volumes/HD2/Development/Repos/xxx/mobile/app/store/auth.ts':
TypeError: Cannot read property 'text' of undefined
    at Scope.addVariable (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/noShadowedVariableRule.js:94:51)
    at cb (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/noShadowedVariableRule.js:192:37)
    at visitNodes (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16631:30)
    at Object.forEachChild (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16910:24)
    at NoShadowedVariableWalker.walk (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/noShadowedVariableRule.js:246:12)
    at Rule.AbstractRule.applyWithWalker (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
    at Rule.apply (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/noShadowedVariableRule.js:33:21)
    at Linter.applyRule (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:214:29)
    at /Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/utils.js:160:29)
The 'one-line' rule threw an error in '/Volumes/HD2/Development/Repos/xxx/mobile/app/store/auth.ts':
TypeError: Cannot read property 'kind' of undefined
    at cb (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/oneLineRule.js:140:30)
    at visitNodes (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16631:30)
    at Object.forEachChild (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16910:24)
    at OneLineWalker.walk (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/oneLineRule.js:148:19)
    at Rule.AbstractRule.applyWithWalker (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
    at Rule.apply (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/oneLineRule.js:34:21)
    at Linter.applyRule (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:214:29)
    at /Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/utils.js:160:29)
    at Linter.getAllFailures (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:155:32)
The 'no-object-literal-type-assertion' rule threw an error in '/Volumes/HD2/Development/Repos/xxx/mobile/app/store/auth.ts':
TypeError: Cannot read property 'kind' of undefined
    at cb (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/noObjectLiteralTypeAssertionRule.js:65:23)
    at visitNodes (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16631:30)
    at Object.forEachChild (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16910:24)
    at walk (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/noObjectLiteralTypeAssertionRule.js:63:15)
    at Rule.AbstractRule.applyWithFunction (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/noObjectLiteralTypeAssertionRule.js:35:21)
    at Linter.applyRule (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:214:29)
    at /Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/utils.js:160:29)
    at Linter.getAllFailures (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:155:32)
The 'interface-over-type-literal' rule threw an error in '/Volumes/HD2/Development/Repos/xxx/mobile/app/views/login.ts':
TypeError: Cannot read property 'kind' of undefined
    at Object.isTypeLiteralNode (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tsutils/typeguard/2.8/node.js:640:17)
    at cb (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/interfaceOverTypeLiteralRule.js:50:65)
    at visitNodes (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16631:30)
    at Object.forEachChild (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/typescript/lib/typescript.js:16910:24)
    at walk (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/interfaceOverTypeLiteralRule.js:49:15)
    at Rule.AbstractRule.applyWithFunction (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/rules/interfaceOverTypeLiteralRule.js:29:21)
    at Linter.applyRule (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:214:29)
    at /Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (/Volumes/HD2/Development/Repos/xxx/mobile/node_modules/tslint/lib/utils.js:160:29)
```

**Comment by chemzqm** [comment]
The issues is from your local tslint, I can't reproduce it.

Consider use https://github.com/neoclide/coc-tslint-plugin instead of coc-tslint.

**Comment by tobydeh** [comment]
Why would this be an issue with 'my local' tslint?

Do you have any recommendations for me to try? If i remove tslint from the project dependencies coc-tslint doesn't start.

**Comment by chemzqm** [comment]
The error comes from your local tslint module.

**Comment by chemzqm** [comment]
Use coc-tslint-plugin, this module is quite limited.

**Comment by tobydeh** [comment]
Ok thank you :)
