### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by zimmicz** [neoclide/coc-tslint#4]
I'm running neovim 0.3.7 with the `release` branch of coc.nvim and coc-tslint installed with `:CocInstall coc-tslint`. However, on opening a .ts file I get the following error:

```
2019-07-03T15:03:24.806 INFO (pid:25256) [plugin] - coc 0.0.72-ede278185a initialized with node: v11.15.0
2019-07-03T15:03:26.673 ERROR (pid:25256) [extensions] - { Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at req (/home/zimmi/.vim/plugged/coc.nvim/build/index.js:60592:21)
    at Object.<anonymous> (/home/zimmi/.config/coc/extensions/node_modules/coc-tslint/node_modules/tslint/lib/utils.js:21:10)
    at Module._compile (/home/zimmi/.vim/plugged/coc.nvim/build/index.js:60613:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19) code: 'MODULE_NOT_FOUND' }
2019-07-03T15:03:26.707 INFO (pid:25256) [services] - registed service "tsserver"
2019-07-03T15:03:26.847 INFO (pid:25256) [services] - service tsserver started

```
I have typescript 3.5.2 installed with `yarn global add typescript`. Is there anything else needed to be done?

**Comment by zimmicz** [comment]
Closing, seems the NODE_PATH was not set correctly.
